### ISSUE TITLE
Sync Realtime Attendance from multiple devices 

### ISSUE THREAD

**Issue by Zaeem6100** [sowrensen/zkconnect#1]
I have a single microservice running and now i have to sync  Realtime  Attendance in it. The zkconnect connects only a single device is it possible to connect multiple devices with the single microservice.

**Comment by sowrensen** [comment]
@Zaeem6100 I don't have access to any device at this moment. I guess you could make it to connect multiple devices. Please feel free to fork the repository and try it out.

**Comment by sowrensen** [comment]
I'm gonna go ahead and close this issue since there is no more interaction.
